### ISSUE TITLE
Without `dist` explicitly set it shows on Android but not on iOS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-cordova#280] opened 2022-08-29 18:31 UTC
e.g:

```
<script> (function (w) { var i = (w.SENTRY_RELEASE = w.SENTRY_RELEASE || {}); i.id = ‘675adc71dca71be2c5e5’; })(this); </script>
```

**Comment by marandaneto** [comment] 2022-08-30 07:47
https://github.com/getsentry/sentry-react-native/blob/c7547e66a21fb9db76a2899f82b7ae2aa07544f4/src/js/integrations/release.ts#L50-L58
That's how it works on RN.

**Comment by souredoutlook** [comment] 2022-08-31 02:52
Hey all, slight confusion here on my part.

Sorry @bruno-garcia for the misleading Slack message.

 The script tag seems to be working as expected, but one thing I noticed was that the `dist` value on Android seems to get added to the events, even if it's not added to the Sentry.init() options. It is present in the config.xml, like so:

`<widget android-versionCode="27696605" id="some_id" ios-CFBundleVersion="27696605" osx-CFBundleVersion="27696605" version="1.0.34" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">`

This is only happening on Android, not iOs. Any advice for how to workaround this?

**Comment by lucas-zimerman** [comment] 2022-08-31 12:54
> Hey all, slight confusion here on my part.
> 
> Sorry @bruno-garcia for the misleading Slack message.
> 
> The script tag seems to be working as expected, but one thing I noticed was that the `dist` value on Android seems to get added to the events, even if it's not added to the Sentry.init() options. It is present in the config.xml, like so:
> 
> `<widget android-versionCode="27696605" id="some_id" ios-CFBundleVersion="27696605" osx-CFBundleVersion="27696605" version="1.0.34" xmlns="http://www.w3.org/ns/widgets" xmlns:android="http://schemas.android.com/apk/res/android" xmlns:cdv="http://cordova.apache.org/ns/1.0">`
> 
> This is only happening on Android, not iOs. Any advice for how to work around this?

Just to be clear, the issue here is the `dist` parameter being set on Android, despite it not being set by the user?

**Comment by lucas-zimerman** [comment] 2022-08-31 13:50
> @lucas-zimerman yes that's the concern. The workaround is to manually remove it from events but this customer would rather it not get set at all if they don't declare it. To my knowledge, this is how sentry-react-native handles this but I might be mistaken.

By the way, do you have a sample that you are testing Cordova? I was going to check what's going on but I found another issue that is not allowing me to validate it on my sample app 😅

**Comment by souredoutlook** [comment] 2022-09-09 18:59
hi @lucas-zimerman 

I don't have a sample app to test this, unfortunately.

I'm going to move forward with recommending they remove the field in beforeSend as a temporary workaround.

**Comment by lucas-zimerman** [comment] 2022-09-28 13:12
@souredoutlook Ok so, I was able to reproduce it and we could do two things:
1) remove the default Dist from the events on Android.
2) when uploading the sourcemaps for Android, we could set the default dist for Android when uploading the sourcemaps if it weren't set by the user.

I believe the second option is more adequate since it'll not generate any break changes if users are using the default dist.
Any thoughts @bruno-garcia ?

**Comment by bruno-garcia** [comment] 2022-11-18 03:02
I'll defer to @kahest

**Comment by kahest** [comment] 2022-11-18 10:16
Thanks for investigating this @lucas-zimerman!
Generally I'd say go with option 2 to prevent breaking things, but that would mean changing this in sentry-cli, right?

**Comment by lucas-zimerman** [comment] 2023-11-24 13:15
Implementing this solution [https://github.com/getsentry/sentry-capacitor/pull/480** **](https://github.com/getsentry/sentry-capacitor/pull/480) will fix this issue

**Comment by ryan953** [comment] 2024-12-14 00:40
https://github.com/getsentry/sentry-capacitor/pull/480 is merged which supposedly fixed the issue. Closing

**Closed by ryan953** 2024-12-14 00:40 UTC
Labels: Platform: Cordova, Status: Backlog
